In [48]:
import PyPDF2
import re
import pandas as pd

In [229]:
file = 'temp (1).pdf'
doc = PyPDF2.PdfReader(file)
page=doc.pages[0]
text = page.extract_text().split('\n')

In [230]:
text

[' ',
 ' ',
 ' \xa0GOVERNMENT OF TAMILNADU  ',
 'REGISTRATION DEPARTMENT  ',
 'தமிழ்நாடு அரசு ',
 'பதிவுத்துைற\xa0',
 'Certificate of Encumbrance on Property  ',
 'ெசாத்து ெதாடர்பான வில்லங்கச் சான்று',
 'S.R.O /சா.ப.அ: Chennai Central Joint I Date / நாள்: 27-May-2023',
 'Document No.& Year/ ஆவண எ ண் மற்றும் ஆண்டு: 1/2023',
 'Sr. ',
 'No./வ. ',
 'எண்Document No.& Year/',
 'ஆவண எ ண் மற்றும் ',
 'ஆண்டுDate of Execution & Date ',
 'of Presentation & Date of ',
 'Registration/ எழுதிக் ெகா ',
 'டுத்த நாள் & தாக்க ல் ',
 'நாள் & பதிவு நாள்Nature/ தன்ைமName of Executant(s)/',
 'எழுதிக்ெகாடுத்தவர்ெபயர்(கள்)Name of Claimant(s)/',
 'எழுதி வாங்கியவர் ',
 'ெபயர்(கள்)Vol.No & Page. No/',
 'ெதாகுதி எண் மற்றும் ',
 'பக்க எண்',
 '1/202302-Jan-2023  ',
 '02-Jan-2023  ',
 '02-Jan-2023Deposit Of Title ',
 'Deeds  1. விஜயன் ',
 '2. வசந்தா ராமபத்ராச்சாரி ',
 '3. வீணா விஜயன் 1. கனரா வ ங்கி -',
 'Consideration Value/ ைகமாற்றுத் ெதாைக:  ',
 '-Market Value/ சந்ைத மதிப்பு: ',
 'ரூ. 3,75,00,000/-PR Number/ முந்ைதய ஆவண எ ண்:  ',
 '297/2022, 298/2022',
 'Schedule 1 Details:  ',
 'Property Type/ ெசாத்தின் வைகப்பாடு: Flats',
 'Village & Street/ கிராமம் மற்றும் ெதரு: Teynampet, Rathna Nagar Main ',
 'RoadSurvey No-Extent/ புல எண்-விஸ்தீர்ணம்: 183, 190, 191, 194, 3856/1PART, ',
 '3856/24 - 854.0 SQUARE FEET',
 'Building Name/ கட்டிடத்தின் ெபயர்: RADIANCE ELITE  ',
 'New Door No./ புதிய கதவு எண்: 23 ',
 'Old Door No./ பைழய கதவு எண்: 12 Floor No./ தள எண்: 3-வது தளம்  ',
 'Plot No./ மைன எண் : 10 C  ',
 'Flat No./ அடுக்குமாடிக் குடியிருப்பு எண்: FLAT NO.302',
 'Schedule Remarks/ ெசாத்து விவரம் ெதாடர்பான குறிப்புைர: ப்ளாட் எண்.302, 3-வ து ',
 'தளம், கட்டிடத்தின் ெபயர் ெரடியன்ஸ் எைலட், மைன எண்.10-சி, பைழய கதவு ',
 'எண்.12, புதிய கதவு எண்.23, ரத்னா நகர் ெமயின் ேராடு, ேதனாம்ேபட்ைட, ெசன்ைன-',
 '600018, ப ைழய சர்ேவ எண்கள்.183, 190, 191 ம ற்றும் 194, பைழய ஆர்.எஸ்.எண்.3856/1 1',
 'எல்ைல விபரங்கள்:  ',
 'கிழக்கு - ஆர்.எஸ்.எண்கள்.3856/12 ம ற்றும் 3856/14 , ேமற்கு - 40 அடி ேராடு ',
 '(ரத்னா நகர் ெமயின் ேராடு) , வடக்கு - மைன எண்.10-பி, ெதற்கு - மைன ',
 'எண்.11',
 '1']

In [233]:
db =[]
for i in range(1,11):
    doc = PyPDF2.PdfReader(f'temp ({i}).pdf')
    page=doc.pages[0]
    text = page.extract_text().split('\n')
    data = {}
    
    data['S.R.O']=(' ').join(text[8].split(' ')[2:-4])
    data['Date']=text[8].split(' ')[-1]
    data['Document No & Year']=text[9].split(':')[1].strip()
    data['Date of Registration']=text[25].strip()
    for i in range(len(text)):
        
        if '-Market Value' in text[i].split('/'):
            data['Market Value']=text[i+1].split(' ')[1].split('/')[0]
        
        try:
            if text[i].split('/')[1]=='-Market Value':
                data['Consideration Value']=text[i].split('/')[0].split(' ')[-1]
        except:
            pass
        if 'Extent' in text[i].split('/')[0].split('-')[-1]:
            data['Survey No-Extent']=text[i].split(':')[-1].strip()
            
        if '-PR Number' in text[i].split('/'):
            data['PR Number']=text[i+1].strip()
            
        if 'Property Type' in text[i].split('/'):
            data['Property Type']=text[i].split(':')[-1].strip()
            
        if 'Village & Street' in text[i].split('/'):
            data['Village & Street']=text[i].split(':')[-1].strip()
            
        if 'Building Name' in text[i].split('/'):
            data['Building Name']=text[i].split(':')[-1].strip()      
            
        if 'New Door No.' in text[i].split('/'):
            data['New Door No']=text[i].split(':')[-1].strip() 
            
        if 'Old Door No.' in text[i].split('/'):
            if 'Floor' in text[i].split(':')[1].split(' '):
                data['Old Door No']=text[i].split(':')[1].split(' ')[1].strip() 
            else:
                data['Old Door No']=text[i].split(':')[-1].strip()
        if 'Floor No.' in text[i].split('/'):
            data['Floor No']=text[i].split(':')[-1].strip()   
            
        if 'Plot No.' in text[i].split('/'):
            data['Plot No']=text[i].split(':')[-1].strip()
            
        if 'Flat No.' in text[i].split('/'):
            data['Flat No']=text[i].split(':')[-1].strip()
         
    db.append(data)

In [236]:
file=pd.DataFrame(db)
file['Market Value']=file['Market Value'].str.replace('Number','')
file

,S.R.O,Date,Document No & Year,Date of Registration,Market Value,PR Number,Property Type,Village & Street,Survey No-Extent,Building Name,New Door No,Old Door No,Plot No,Flat No,Consideration Value
0,Chennai Central Joint I,27-May-2023,1/2023,02-Jan-2023,"3,75,00,000","297/2022, 298/2022",Flats,"Teynampet, Rathna Nagar Main","183, 190, 191, 194, 3856/1PART,",RADIANCE ELITE,23,12,10 C,FLAT NO.302,NaN
1,Chennai Central Joint I,27-May-2023,2/2023,02-Jan-2023,"4,50,00,000",561/2007,Plot With Building,"Teynampet, Masilamani Road &",3746/6 - 2767.0 SQUARE FEET,சுவாமி பவன ம்,2,"12,8",NaN,NaN,NaN
2,Chennai Central Joint I,27-May-2023,3/2023,02-Jan-2023,"78,95,808","16/2005, 17/2005",Plot With Building,"Teynampet, Seethammal Colony","3766/14, 3766/3PART - 1500.0",NaN,NaN,NaN,NaN,NaN,NaN
3,Chennai Central Joint I,27-May-2023,4/2023,02-Jan-2023,,"547/1974, 557/1968, 598/2012, 733/1976",Plot With Building,"Teynampet, Gopalapuram 8th","1253/2, 1253/3 - 2600.5 SQUARE FEET",NaN,7,6 1,NaN,NaN,NaN
4,Chennai Central Joint I,27-May-2023,5/2023,03-Jan-2023,"2,70,00,000",1642/2022,Flats,"Teynampet, Kasthuri Ranga","1578/11, 1578/3PART - 1257.0 SQUARE",NaN,NaN,NaN,NaN,NaN,NaN
5,Chennai Central Joint I,27-May-2023,6/2023,03-Jan-2023,,1264/2021,Plot With Building,"Teynampet, Avvai Shanmugam","108/7, 109/14 - 4611.0 SQUARE",NaN,NaN,NaN,NaN,NaN,"1,05,00,000"
6,Chennai Central Joint I,27-May-2023,7/2023,04-Jan-2023,,879/2008,Plot With Building,"Teynampet, Veenus Colony 2nd",1553/1 - 1451.9 SQUARE FEET,NaN,DOOR NO.21,OLD NO.9 1,NaN,NaN,"37,00,000"
7,Chennai Central Joint I,27-May-2023,8/2023,04-Jan-2023,,169/2017,Plot With Building,"Teynampet, Veenus Colony 2nd",1553/1 - 1451.9 SQUARE FEET,NaN,DOOR NO.21,OLD NO.9,NaN,NaN,"25,00,000"
8,Chennai Central Joint I,27-May-2023,9/2023,04-Jan-2023,"1,90,00,000",1127/2002,Plot With Building,"Teynampet, Avvai Shanmugam","108/7, 109/14 - 4611.0 SQUARE FEET",NaN,240A,135,NaN,NaN,NaN
9,Chennai Central Joint I,27-May-2023,10/2023,04-Jan-2023,"7,50,00,000",1097/1984,Plot With Building,"Teynampet, Goverthan Singh",133/9 - 2779.0 SQUARE FEET1,NaN,NaN,NaN,NaN,NaN,NaN

In [237]:
file.to_csv('pdf_to_csv.csv',index=False)